# Generated by Django 4.1.1 on 2022-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='refresh',
            field=models.TextField(unique=True, verbose_name='Refresh token bcrypt'),
        ),
    ]
